In [3]:
!pip install kaggle

Requirement already satisfied: kaggle in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (1.7.4.5)
Requirement already satisfied: webencodings in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: urllib3>=1.15.1 in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (2.7.0)
Requirement already satisfied: python-slugify in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: charset-normalizer in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (3.4.9)
Requirement already satisfied: protobuf in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (7.35.1)
Requirement already satisfied: bleach in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (6.4.0)
Requirement already satisfied: certifi>=14.05.14 in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (2026.6.17)
Requirement already satisfied: idna in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (3.18)
Requirement already satisfied: python-dateutil>=2.5.3 in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: setuptools>=21.0.0 in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (65.5.0)
Requirement already satisfied: text-unidecode in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: six>=1.10 in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (1.17.0)
Requirement already satisfied: requests in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (2.34.2)
Requirement already satisfied: tqdm in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from kaggle) (4.69.0)
Requirement already satisfied: colorama in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from tqdm->kaggle) (0.4.6)

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import zipfile

with zipfile.ZipFile('../data/raw/retail-orders.zip', 'r') as zip_ref:
    zip_ref.extractall('../retail-orders')

In [10]:
#read the data
import pandas as pd
df = pd.read_csv('../retail-orders/orders.csv', na_values=['Not Available', 'unknown'])

In [11]:
df.head(20)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3
10,11,2023-03-31,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Tables,FUR-TA-10001539,1470,1710,9,3
11,12,2023-12-25,NaN,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002033,750,910,4,3
12,13,2022-02-11,Standard Class,Consumer,United States,Concord,North Carolina,28027,South,Office Supplies,Paper,OFF-PA-10002365,20,20,3,3
13,14,2023-07-18,Standard Class,Consumer,United States,Seattle,Washington,98103,West,Office Supplies,Binders,OFF-BI-10003656,360,410,3,2
14,15,2023-11-09,NaN,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Appliances,OFF-AP-10002311,60,70,5,5
15,16,2022-06-18,Standard Class,Home Office,United States,Fort Worth,Texas,76106,Central,Office Supplies,Binders,OFF-BI-10000756,0,0,3,5
16,17,2022-02-04,Standard Class,Consumer,United States,Madison,Wisconsin,53711,Central,Office Supplies,Storage,OFF-ST-10004186,610,670,6,3
17,18,2023-08-04,Second Class,Consumer,United States,West Jordan,Utah,84084,West,Office Supplies,Storage,OFF-ST-10000107,60,60,2,4
18,19,2022-01-23,Second Class,Consumer,United States,San Francisco,California,94109,West,Office Supplies,Art,OFF-AR-10003056,10,10,2,4
19,20,2022-01-11,Second Class,Consumer,United States,San Francisco,California,94109,West,Technology,Phones,TEC-PH-10001949,170,210,3,3

In [12]:
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [13]:
df.isna().sum()

Order Id            0
Order Date          0
Ship Mode           6
Segment             0
Country             0
City                0
State               0
Postal Code         0
Region              0
Category            0
Sub Category        0
Product Id          0
cost price          0
List Price          0
Quantity            0
Discount Percent    0
dtype: int64

In [14]:
#rename the column - lower case and underscore
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [15]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5

In [16]:
#check columns and see if derived columns can be created
df['discount'] = df['list_price']*df['discount_percent']*.01

In [17]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0

In [18]:
df['sale_price'] = df['list_price'] - df['discount']

In [19]:
df['profit'] = df['sale_price'] - df['cost_price']

In [20]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [21]:
#convert date datatype
df['order_date'] = pd.to_datetime(df['order_date'], format='%Y-%m-%d')

In [22]:
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [23]:
#drop columns - now not needed
df.drop(columns = ['list_price', 'cost_price', 'discount_percent'], inplace=True)

In [24]:
df.head(5)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0

In [25]:
!pip install sqlalchemy

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.51-cp310-cp310-win_amd64.whl (2.1 MB)
Collecting greenlet>=1
  Using cached greenlet-3.5.3-cp310-cp310-win_amd64.whl (238 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (from sqlalchemy) (4.16.0)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.5.3 sqlalchemy-2.0.51

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
!pip install pyodbc

Requirement already satisfied: pyodbc in d:\data_science_project_2\data-science_resumes\data-analysis\venv\lib\site-packages (5.3.0)

[notice] A new release of pip available: 22.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [30]:
#instantiate the sql server
import sqlalchemy as sal
engine = sal.create_engine('mssql://Foxy_Saravana/master?driver=ODBC+DRIVER+17+FOR+SQL+SERVER')
conn = engine.connect()

InterfaceError: (pyodbc.InterfaceError) ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Data source name not found and no default driver specified (0) (SQLDriverConnect)')
(Background on this error at: https://sqlalche.me/e/20/rvf5)

In [ ]:
#load the data
df.to_sql('df_orders', con=conn, index=False, if_exists='append')

In [29]:
!{sys.executable} -m pip install pyodbc

Collecting pyodbc
  Downloading pyodbc-5.3.0-cp310-cp310-win_amd64.whl.metadata (2.8 kB)
Downloading pyodbc-5.3.0-cp310-cp310-win_amd64.whl (69 kB)
Installing collected packages: pyodbc
Successfully installed pyodbc-5.3.0

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: C:\Users\akhil\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip